name: tasktick
description: "A new Flutter project."
publish_to: 'none'  # Ensures the package is not accidentally published to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.5.0
  msh_checkbox: ^1.1.1 
  uuid: ^3.0.6
  flutter_launcher_icons: "^0.9.2"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true 
  ios: true
  image_path: "images/icon.png"